# Introduction to Scitkit-Learn (sklearn)
This notebook demonstrates some of the most useful functions of the Scikit-Learn library.

What is covered:
    
0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for the problem
3. Fit the model/algorithm and use it to make predictions on the data
4. Model evaluation
5. Model improvement
6. Save and load the trained model
7. Put it all together

In [1]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 0. An end-to-end Scikit-Learn workflow

In [2]:
# 1. Get the data ready
heart_disease = pd.read_csv('heart-disease.csv')
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
# Create X (feature matrix)
X = heart_disease.drop('target', axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [4]:
# Create y (labels)
y = heart_disease['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [5]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# Keep the default hyperparameters
clf.get_params() # return hyperparameters

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
# Illustrating how train_test_split works:
# Make a small X and y dataset
Xs, ys = np.arange(10).reshape(5,2), np.array(range(5))
Xs, ys

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([0, 1, 2, 3, 4]))

In [8]:
# Split the data
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.33)
Xs_train, Xs_test, ys_train, ys_test

(array([[4, 5],
        [2, 3],
        [6, 7]]),
 array([[8, 9],
        [0, 1]]),
 array([2, 1, 3]),
 array([4, 0]))

In [9]:
# 3. Fit the model to the training data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [11]:
# Shape of dataset
X_train.shape, X_test.shape, y_train.shape, y_test.shape, len(heart_disease), len(heart_disease)*0.2

((242, 13), (61, 13), (242,), (61,), 303, 60.6)

In [12]:
# Make a prediction on a random dataset (requires same number of columns as X, rows can be anything - they are equivalent to sampels)
X_random = np.random.rand(242, 13)
y_label = clf.predict(X_random)

In [13]:
y_label.shape

(242,)

In [14]:
# Get prediction on actual test dataset
y_preds = clf.predict(X_test)
y_preds

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1])

In [15]:
y_test

154    1
114    1
76     1
248    0
192    0
      ..
120    1
130    1
98     1
211    0
104    1
Name: target, Length: 61, dtype: int64

In [16]:
# 4. Evaluate the model on training and test data
clf.score(X_train, y_train)

1.0

In [17]:
# Test data
clf.score(X_test, y_test)

0.8524590163934426

In [18]:
# Use random features data and use y_train as true label
clf.score(X_random, y_train)

0.4834710743801653

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.83      0.79      0.81        24
           1       0.87      0.89      0.88        37

    accuracy                           0.85        61
   macro avg       0.85      0.84      0.84        61
weighted avg       0.85      0.85      0.85        61



In [20]:
confusion_matrix(y_test, y_preds)

array([[19,  5],
       [ 4, 33]])

In [21]:
accuracy_score(y_test, y_preds) # same return as .score

0.8524590163934426

In [22]:
# 5. Model improvements
# Try different amount of n_estimators
np.random.seed(0)
for i in range(10, 100, 10):
    print(f'Trying with {i} estimators...')
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(X_train, y_train)
    print(f'Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%')
    print(' ')

Trying with 10 estimators...
Model accuracy on test set: 80.33%
 
Trying with 20 estimators...
Model accuracy on test set: 77.05%
 
Trying with 30 estimators...
Model accuracy on test set: 73.77%
 
Trying with 40 estimators...
Model accuracy on test set: 83.61%
 
Trying with 50 estimators...
Model accuracy on test set: 78.69%
 
Trying with 60 estimators...
Model accuracy on test set: 80.33%
 
Trying with 70 estimators...
Model accuracy on test set: 83.61%
 
Trying with 80 estimators...
Model accuracy on test set: 80.33%
 
Trying with 90 estimators...
Model accuracy on test set: 81.97%
 


In [23]:
# 6. Save a model and load it
import pickle

pickle.dump(clf, open('random_forest_model1.pkl', 'wb')) # wb - write binary

In [24]:
# Load the model
loaded_model = pickle.load(open('random_forest_model1.pkl', 'rb')) # rb - read binary
loaded_model.score(X_test, y_test)

0.819672131147541

## 1. Getting data ready to be used with matchine learning

Three main things to do:
1. Split the data into features and labels (usually `X` & `y`)
2. Filling (also called imputing) or disregarding missing values
3. Converting non-numerical values into numerical values (also called feature encoding)

In [25]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [26]:
# Features
X = heart_disease.drop('target', axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [27]:
# Labels
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [28]:
# Split into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [29]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [30]:
X.shape

(303, 13)

In [31]:
len(X)

303

In [32]:
X.shape[0] * 0.8

242.4

In [33]:
len(heart_disease)

303

## 1.1 Make sure it's all numerical

In [34]:
car_sales = pd.read_csv('car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [35]:
len(car_sales)

1000

In [36]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [37]:
# Features
X = car_sales.drop('Price', axis=1)
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [38]:
# Labels
y = car_sales['Price']
y.head()

0    15323
1    19943
2    28343
3    13434
4    14043
Name: Price, dtype: int64

In [39]:
# Split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [40]:
car_sales['Doors'].value_counts()

4    856
5     79
3     65
Name: Doors, dtype: int64

In [41]:
# Turn the categories into numbers (method #1)
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                   one_hot,
                                   categorical_features
                                 )],
                                remainder='passthrough') # apply to categorical_features, rest passthrough (leave unchanged)
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [44]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [46]:
pd.DataFrame(transformed_X).head()

0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0

In [48]:
# Turn the categories into numbers (method #2)
dummies = pd.get_dummies(car_sales[['Make', 'Colour', 'Doors']])
dummies.head()

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4         0           1            0            0             0   
1      5         1           0            0            0             0   
2      4         0           1            0            0             0   
3      4         0           0            0            1             0   
4      3         0           0            1            0             0   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0            0             0           0             1  
1            1             0           0             0  
2            0             0           0             1  
3            0             0           0             1  
4            1             0           0             0

In [53]:
# Refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

In [54]:
# Build ML model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.3235867221569877

### 1.2 How to deal with missing values:

1. Fill them with some value (also known as imputation).
2. Remove the samples with missing data altogether.

In [64]:
# Import data
car_sales_missing = pd.read_csv('car-sales-extended-missing-data.csv')

# Count number of missing values
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

#### Option #1: Fill missing data with Pandas

In [84]:
# Fill the 'Make' column
car_sales_missing['Make'].fillna('missing', inplace=True)

# Fill the 'Colour' column
car_sales_missing['Colour'].fillna('missing', inplace=True)

# Fill the 'Odometer (KM)' column with the average
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(), inplace=True)

In [88]:
# Find the most frequent door number
car_sales_missing['Doors'].value_counts()

4.0    811
5.0     75
3.0     64
Name: Doors, dtype: int64

In [92]:
# Fill the 'Doors' column with the most frequent number
car_sales_missing['Doors'].fillna(4, inplace=True)

# Remove all rows without prices
car_sales_missing.dropna(subset=['Price'], inplace=True)

# Number of records after removal
len(car_sales_missing)

950

In [93]:
# Create X & y
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [67]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                   one_hot,
                                   categorical_features
                                 )],
                                remainder='passthrough') # apply to categorical_features, rest passthrough (leave unchanged)
transformed_X = transformer.fit_transform(X)
transformed_X

ValueError: Input contains NaN