In [214]:
import numpy as np

## Datatypes & Attributes

In [215]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [216]:
type(a1)

numpy.ndarray

In [217]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [218]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [219]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [220]:
# shape: 1 row, 3 columns
a1.shape

(3,)

In [221]:
# shape: 2 rows, 3 columns
a2.shape

(2, 3)

In [222]:
# shape: 2 rows, 3 columns, 3 depth
a3.shape

(2, 3, 3)

In [223]:
# shape works as follows:
# brackets:
#     outermost: arrays
#     middle: rows
#     innermost: columns

# always start counting from the inside out

# a3:
# (2 arrays, 3 rows, 3 columns)

# access 15 -> array #2, row #2, column #3

a3[1][1][2]

15

In [224]:
# a1, a2, a3 dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [225]:
# number of elements
a1.size, a2.size, a3.size

(3, 6, 18)

In [226]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [227]:
# Create a dataframe from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [228]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

## 2. Creating Arrays

In [229]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [230]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [231]:
# same as range but fills an array with the range
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [232]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7],
       [7, 8, 1, 5, 9]])

In [233]:
random_array.size

15

In [234]:
random_array.shape

(3, 5)

In [235]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832]])

In [236]:
random_array2.shape

(5, 3)

In [237]:
# .rand is the same as .random, the only difference is that random takes args as tuple whereas rand as separate args
random_array3 = np.random.rand(5,3)
random_array3

array([[0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547]])

In [238]:
# Pseudo-random numbers
# Use seed so that random numbers are the same at every run
np.random.seed(5)
random_array4 = np.random.randint(0,10,size=(5,2))
random_array4

array([[3, 6],
       [6, 0],
       [9, 8],
       [4, 7],
       [0, 0]])

## 3. Viewing arrays and matrices

In [239]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [240]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
# View the second and third column of the second array
a3[1,:,1:]

array([[11, 12],
       [14, 15],
       [17, 18]])

In [242]:
# View the last row of all arrays
a3[:,2,:]

array([[ 7,  8,  9],
       [16, 17, 18]])

In [243]:
# View the top 2 quadrant of each array
a3[:,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [244]:
#View the last 2 cells of each array
a3[:,-1,-2:]

array([[ 8,  9],
       [17, 18]])

In [245]:
#View the last 2 cells and rows of each array
a3[:,-2:,-2:]

array([[[ 5,  6],
        [ 8,  9]],

       [[14, 15],
        [17, 18]]])

In [246]:
np.random.seed(3)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[8, 9, 3, 8, 8],
         [0, 5, 3, 9, 9],
         [5, 7, 6, 0, 4],
         [7, 8, 1, 6, 2]],

        [[2, 1, 3, 5, 8],
         [1, 8, 7, 8, 1],
         [0, 5, 4, 1, 5],
         [4, 7, 6, 0, 0]],

        [[9, 2, 4, 5, 8],
         [8, 7, 5, 1, 1],
         [1, 5, 5, 7, 4],
         [3, 0, 0, 0, 0]]],


       [[[2, 2, 7, 0, 5],
         [0, 1, 4, 1, 2],
         [2, 4, 8, 0, 6],
         [0, 4, 1, 5, 1]],

        [[8, 8, 7, 0, 0],
         [9, 1, 7, 8, 7],
         [4, 0, 0, 4, 3],
         [0, 8, 2, 7, 2]],

        [[1, 3, 2, 4, 1],
         [2, 2, 7, 3, 4],
         [1, 6, 7, 9, 1],
         [0, 0, 5, 8, 4]]]])

In [247]:
# View the element from the second last row and column of the last array; ==> 9
a4[-1][-1][-2][-2]

9

In [248]:
# View the bottom, middle 3x3 array from the last outer array's middle array; ==> [[1,7,8],[0,0,4],[8,2,7]]
a4[-1,1,1:,1:-1]

array([[1, 7, 8],
       [0, 0, 4],
       [8, 2, 7]])

In [249]:
a4.shape, a4.size

((2, 3, 4, 5), 120)

In [250]:
# Get the first 4 numbers of each array
a4[:,:,:,:4]

array([[[[8, 9, 3, 8],
         [0, 5, 3, 9],
         [5, 7, 6, 0],
         [7, 8, 1, 6]],

        [[2, 1, 3, 5],
         [1, 8, 7, 8],
         [0, 5, 4, 1],
         [4, 7, 6, 0]],

        [[9, 2, 4, 5],
         [8, 7, 5, 1],
         [1, 5, 5, 7],
         [3, 0, 0, 0]]],


       [[[2, 2, 7, 0],
         [0, 1, 4, 1],
         [2, 4, 8, 0],
         [0, 4, 1, 5]],

        [[8, 8, 7, 0],
         [9, 1, 7, 8],
         [4, 0, 0, 4],
         [0, 8, 2, 7]],

        [[1, 3, 2, 4],
         [2, 2, 7, 3],
         [1, 6, 7, 9],
         [0, 0, 5, 8]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [251]:
a1

array([1, 2, 3])

In [252]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [253]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [254]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [255]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [256]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [257]:
a2 - ones

array([[0. , 1. , 2.3],
       [3. , 4. , 5.5]])

In [258]:
# floor division
a2 // ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [259]:
a2 * zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [260]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [261]:
a1

array([1, 2, 3])

In [262]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [263]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [264]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [265]:
# a2 * a3 won't work due to incompatible shapes

#### Broadcasting rules:
When operating on two arrays, NumPy compares their shapes element-wise. 
It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when:

1) they are equal, or

2) one of them is 1

In [266]:
# Example that works:
# Image  (3d array): 256 x 256 x 3
# Scale  (1d array):             3
# Result (3d array): 256 x 256 x 3

#### Reshaping so that broadcasting works
![](numpy-manipulation-reshape-function-image-1.png)

In [267]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [268]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [269]:
np.reshape(a2,(3,2))

array([[1. , 2. ],
       [3.3, 4. ],
       [5. , 6.5]])

In [270]:
np.reshape(a2,(2,3,1))

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [271]:
a3 * np.reshape(a2,(2,3,1))

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

### Aggregation
Aggregation = performing the same operation on a number of things

In [272]:
listy_list = [1,2,3]
listy_list

[1, 2, 3]

In [273]:
type(listy_list)

list

In [274]:
sum(listy_list)

6

In [275]:
np.sum(listy_list)

6

In [276]:
a1

array([1, 2, 3])

In [277]:
sum(listy_list)

6

In [278]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays(`np.sum()`)

In [279]:
# Create a massive NumPy array
massive_array = np.random.random(10000000)
massive_array.size

10000000

In [280]:
massive_array[:10]

array([0.34992523, 0.77273869, 0.89649666, 0.78573034, 0.28340737,
       0.88190845, 0.54538261, 0.82802212, 0.23369201, 0.20287765])

In [281]:
%timeit sum(massive_array) # Python's sum
%timeit np.sum(massive_array) # NumPy's sum

2.36 s ± 540 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.88 ms ± 345 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [282]:
# Time difference
2.31*1000 / 5.79

398.9637305699482

In [283]:
# Create a massive Python list
massive_list = list(range(10000000))
len(massive_list)

10000000

In [284]:
%timeit sum(massive_list) # Python's sum
%timeit np.sum(massive_list) # NumPy's sum

61.9 ms ± 958 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
689 ms ± 17.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [285]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [286]:
np.mean(a2)

3.6333333333333333

In [287]:
np.min(a2), np.max(a2), np.var(a2), np.std(a2)

(1.0, 6.5, 3.3222222222222224, 1.8226964152656422)

In [288]:
np.sqrt(np.var(a2)), np.std(a2)

(1.8226964152656422, 1.8226964152656422)

In [289]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([0, 2, 4, 6, 8, 10])

In [291]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
plt.hist(high_var_array)
plt.show() # without this plot might not be shown and data will be shown

In [ ]:
plt.hist(low_var_array)
plt.show()

In [ ]:
np.mean(low_var_array), np.mean(high_var_array)

In [ ]:
np.std(low_var_array), np.std(high_var_array)

In [ ]:
np.var(low_var_array), np.var(high_var_array)

In [ ]:
np.min(low_var_array), np.min(high_var_array)

In [ ]:
np.max(low_var_array), np.max(high_var_array)

### Reshaping & transposing

In [ ]:
a2.shape

In [ ]:
a3.shape

In [ ]:
a2_reshape = a2.reshape((2,3,1))
a2_reshape.shape

In [ ]:
a2_reshape*a3

In [ ]:
# Transpose: switches axises; reverses order of axis
# indexing: a_matrix_row_column becomes a_column_row_matrix

In [ ]:
a2

In [ ]:
a2.T

In [ ]:
a2.T.shape, a2.shape

In [ ]:
a3.T.shape, a3.shape

In [ ]:
a3

In [ ]:
a3.T

In [ ]:
# element 100 => 001 (matrix 1, row 0, column 0 => matrix 0, row 0, column 1)
# element 112 => 211 (matrix 1, row 1, column 2 => matrix 2, row 1, column 1)

## Dot product
![](dot-product.png)

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1, mat2

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
mat2_reshape = mat2.reshape((3,5))
mat2_reshape

In [ ]:
mat1

In [ ]:
# Dot product: dimensions on the inside (last dimension first product and first dimension last product) must match
np.dot(mat1, mat2_reshape)

In [ ]:
mat2.T

In [ ]:
np.dot(mat1, mat2.T)

## Dot product example

In [332]:
np.random.seed(5)
sales = np.random.randint(20, size=(5,3))
sales

array([[ 3, 14, 15],
       [ 6, 16,  9],
       [ 8,  4,  7],
       [16, 16,  7],
       [12, 15, 17]])

In [333]:
# Create a sales dataframe
sales_dataframe = pd.DataFrame(sales,
                              index=['Monday','Tuesday','Wednesday','Thursday','Friday'],
                              columns=['Almond Butter','Peanut Butter','Cashew Butter'])
sales_dataframe

Almond Butter  Peanut Butter  Cashew Butter
Monday                 3             14             15
Tuesday                6             16              9
Wednesday              8              4              7
Thursday              16             16              7
Friday                12             15             17

In [334]:
np.random.seed(0)
prices = np.random.randint(1,10,size=(1,3))
prices

array([[6, 1, 4]])

In [335]:
prices_dataframe = pd.DataFrame(prices,
                               index=['Price'],
                               columns=sales_dataframe.columns)
prices_dataframe

Almond Butter  Peanut Butter  Cashew Butter
Price              6              1              4

In [336]:
total_price = np.dot(sales,prices.T)
total_price

array([[ 92],
       [ 88],
       [ 80],
       [140],
       [155]])

In [337]:
income_series = pd.Series(total_price[:,0],index=sales_dataframe.index)
income_series

Monday        92
Tuesday       88
Wednesday     80
Thursday     140
Friday       155
dtype: int64

In [338]:
sales_dataframe['Total income'] = income_series
sales_dataframe

Almond Butter  Peanut Butter  Cashew Butter  Total income
Monday                 3             14             15            92
Tuesday                6             16              9            88
Wednesday              8              4              7            80
Thursday              16             16              7           140
Friday                12             15             17           155

In [348]:
np.random.seed(0)
price_and_tax = np.random.randint(1,10,size=(2,3))
price_and_tax

array([[6, 1, 4],
       [4, 8, 4]])

In [342]:
totals = np.dot(sales,price_and_tax.T)
totals

array([[ 92, 184],
       [ 88, 188],
       [ 80,  92],
       [140, 220],
       [155, 236]])

In [343]:
totals_dataframe = pd.DataFrame(totals,
                               index=sales_dataframe.index,
                               columns=['Total income','Total revenue'])
totals_dataframe

Total income  Total revenue
Monday               92            184
Tuesday              88            188
Wednesday            80             92
Thursday            140            220
Friday              155            236

In [347]:
sales_dataframe = pd.concat([sales_dataframe.drop('Total income',axis=1), totals_dataframe],axis=1)

sales_dataframe

Almond Butter  Peanut Butter  Cashew Butter  Total income  \
Monday                 3             14             15            92   
Tuesday                6             16              9            88   
Wednesday              8              4              7            80   
Thursday              16             16              7           140   
Friday                12             15             17           155   

           Total revenue  
Monday               184  
Tuesday              188  
Wednesday             92  
Thursday             220  
Friday               236

In [351]:
# add price and tax to dataframe for display
price_and_tax_dataframe = pd.DataFrame(price_and_tax,
                                      columns=prices_dataframe.columns,
                                      index=['Price','Tax'])
price_and_tax_dataframe

Almond Butter  Peanut Butter  Cashew Butter
Price              6              1              4
Tax                4              8              4

In [353]:
# Dataframe displaying everything
pd.concat([sales_dataframe, price_and_tax_dataframe],axis=0)

Almond Butter  Peanut Butter  Cashew Butter  Total income  \
Monday                 3             14             15          92.0   
Tuesday                6             16              9          88.0   
Wednesday              8              4              7          80.0   
Thursday              16             16              7         140.0   
Friday                12             15             17         155.0   
Price                  6              1              4           NaN   
Tax                    4              8              4           NaN   

           Total revenue  
Monday             184.0  
Tuesday            188.0  
Wednesday           92.0  
Thursday           220.0  
Friday             236.0  
Price                NaN  
Tax                  NaN